title: Why Not Games

author:
  name: Nikhil Murthy
  email: murthynik1@gmail.com

description: Why Not Games makes independent video games that expand what the medium can say.

show_excerpts: false

minima:
  skin: dark
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/murthynikhil" }
    - { platform: youtube, user_url: "https://www.youtube.com/channel/UCoFEuEueEt1Z2L-CQM8Uopw" }

remote_theme: jekyll/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag