title: Why Not Games
description: Why Not Games makes independent video games that expand what the medium can say.

author:
  name: Nikhil Murthy
  email: "murthynik1@gmail.com"

minima:
  skin: dark
  social_links:
    twitter: murthynikhil
    youtube: Nikhil Murthy
    youtube_channel: UCoFEuEueEt1Z2L-CQM8Uopw
    youtube_channel_name: Nikhil Murthy

theme: minima