title: Why Not Games

author: Nikhil Murthy

description: Why Not Games makes independent video games that expand what the medium can say.

show_excerpts: false

minima:
  skin: dark
  social_links:
    twitter: murthynikhil
    youtube_channel: UCoFEuEueEt1Z2L-CQM8Uopw
    youtube_channel_name: Nikhil Murthy

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag